
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: blankblog_development

test:
  <<: *default
  database: blank_blog_test

#
production:
  <<: *default
  database: blankblog_production
  username: blankblog
  password: <%= ENV['BLANKBLOG_DATABASE_PASSWORD'] %>